version: '3'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    restart: always
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi-app
